package com.dokkaebistudio.tacticaljourney.enemies.enums;

public enum EnemyMoveStrategy {
	STANDING_STILL,
	MOVE_TOWARD_PLAYER,
	TRIBESMAN_SCOUT_STRATEGY,
	MOVE_RANDOMLY,
	MOVE_RANDOMLY_BUT_ATTACK_IF_POSSIBLE,
	MOVE_RANDOMLY_BUT_ATTACK_FROM_RANGE_IF_POSSIBLE;
}