package com.dokkaebistudio.tacticaljourney.creature.enemies.enums;

public enum AIMoveStrategy {
	STANDING_STILL,
	MOVE_TOWARDS_TARGET,
	TRIBESMAN_SCOUT_STRATEGY,
	MOVE_RANDOMLY,
	MOVE_RANDOMLY_BUT_ATTACK_IF_POSSIBLE,
	MOVE_RANDOMLY_BUT_ATTACK_FROM_RANGE_IF_POSSIBLE;
}